apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepull-error-demo
  namespace: troubleshooting
  labels:
    app: imagepull-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepull-demo
  template:
    metadata:
      labels:
        app: imagepull-demo
    spec:
      containers:
        - name: nginx
          image: nginx:this-tag-does-not-exist
          ports:
            - containerPort: 80
